#!/usr/bin/env bash

set -euo pipefail

status_file="$(mktemp)"

cleanup() {
  rm -f "${status_file}"
  supabase stop --no-backup >/dev/null 2>&1 || true
}
trap cleanup EXIT

supabase start --exclude "edge-runtime,imgproxy,logflare,mailpit,postgres-meta,realtime,storage-api,studio,supavisor,vector"
supabase db reset
supabase db lint --local --level warning --fail-on error

supabase status -o env \
  --override-name api.url=SUPABASE_URL \
  --override-name auth.anon_key=SUPABASE_ANON_KEY \
  --override-name auth.service_role_key=SUPABASE_SERVICE_ROLE_KEY \
  >"${status_file}"

set -a
# The file is generated by the local Supabase CLI and contains only ephemeral local values.
# shellcheck disable=SC1090
source "${status_file}"
set +a

node scripts/validate-supabase-m0.mjs
